export const mockProduct = {
  img: "/images/mock.png",
  imgAlt: "battery",
  name: "Bateria EV",
  model: "CCP811 (NMC 811 Chemistry)",
  type: "Bateria",
  id: "EVB-AETG-2023-07-...",
  producer: "CustomCells SE",
  dateOfProduction: "2023-07-15",
  placeOfProduction: "Francja",
  dateOfInstallation: "2023-08-01",
  vehicle: "Audi e-tron GT (2023)",
  capacity: { key: "Pojemność nominalna", value: "50 Ah" },
  voltage: { key: "Napięcie nominalne", value: "20 V" },
  weight: { key: "Masa baterii", value: "51 g" },
  size: { key: "Wymiary baterii", value: "1.5m x 1m x 1.5m" },
  materials: [
    { name: "Lit", amount: 2 },
    { name: "Kobalt", amount: 3 },
    { name: "Nikiel", amount: 1 },
  ],
  carbonFootprint: 40,
  harmfulSubstances: ["Ni"],
}
